import { z } from 'zod';
import { isValidDateString } from '../dates';

/** UUID v4 is generated by the application (`crypto.randomUUID()`), never by the database. */
export const uuidSchema = z.string().uuid({ message: 'Must be a UUID' });

/**
 * A calendar date on the wire.
 *
 * Two checks, because either alone is insufficient: the regex rejects `2026-3-1` and
 * `2026-03-26T00:00:00Z`, and the calendar check rejects `2026-02-31` and `2026-13-01`,
 * which a regex will happily wave through. See `isValidDateString` for why this is not
 * done by parsing into a `Date`.
 */
export const dateStringSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Must be a date in YYYY-MM-DD format' })
  .refine(isValidDateString, { message: 'Must be a real calendar date' });

/**
 * An instant, as opposed to a calendar date — `createdAt` / `updatedAt` only.
 *
 * The distinction is the entire point of §3.1: *when a row was written* is a moment in
 * time (`timestamptz`, ISO 8601); *when a guest arrives* is a date on a calendar.
 * `offset: true` because a client may legitimately send `+02:00` rather than `Z`.
 */
export const isoDateTimeSchema = z.string().datetime({ offset: true });

const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;

/**
 * Offset pagination (§3.5). Cursor pagination is the more scalable design and is noted
 * in the README as a deliberate non-choice: at this dataset size it buys nothing and
 * costs a less demoable API.
 *
 * `z.coerce` because these arrive as query strings. Over-large limits are rejected
 * rather than silently clamped — a client asking for 1000 rows and receiving 100 with
 * no signal is a harder bug to notice than a 400.
 */
export const paginationQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE),
});

export const paginationMetaSchema = z.object({
  page: z.number().int().min(1),
  limit: z.number().int().min(1),
  total: z.number().int().min(0),
  totalPages: z.number().int().min(0),
});

/**
 * The list envelope of §3.5, parameterised by its item schema, so every list endpoint
 * is shaped identically without restating `{ data, pagination }` five times.
 */
export function paginatedSchema<ItemSchema extends z.ZodTypeAny>(itemSchema: ItemSchema) {
  return z.object({
    data: z.array(itemSchema),
    pagination: paginationMetaSchema,
  });
}

export const PAGINATION_DEFAULTS = {
  page: 1,
  limit: DEFAULT_PAGE_SIZE,
  maxLimit: MAX_PAGE_SIZE,
} as const;
